services:
  server:
    build: ./server
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app

  client:
    build: ./client
    env_file: .env
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

networks:
  default:
    name: anglonyt-network
    driver: bridge