services:
  server:
    build: ./server
    env_file: .env
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "--reload", "--workers=1", "--timeout=120", "app:create_app()"]

  client:
    build: ./client
    env_file: .env
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]